// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeveloperNews
{
    internal sealed partial class Vsix
    {
        public const string Id = "36cfa8d9-bd14-4d32-a8a6-34133aa2309d";
        public const string Name = "Daily News";
        public const string Description = @"Shows the developer news from the Visual Studio blog and other sources in a tool window inside Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "news, rss, feed";
    }
}
