// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeveloperNews
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDeveloperNewsPackageString = "cf0f01e7-96a3-4245-a561-76353cddf32d";
        public static Guid guidDeveloperNewsPackage = new Guid(guidDeveloperNewsPackageString);

        public const string guidDeveloperNewsPackageCmdSetString = "257fd01e-353b-43a2-a48a-48fccf3c536f";
        public static Guid guidDeveloperNewsPackageCmdSet = new Guid(guidDeveloperNewsPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NewsWindowCommandId = 0x0100;
    }
}